// SPDX-FileCopyrightText: Copyright The Thingsboard Authors
// SPDX-License-Identifier: Apache-2.0
package org.thingsboard.server.common.data.rbac;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.io.Serial;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Schema
@Data
public class RbacUserGroup implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    @Schema(description = "Unique identifier of the group, generated by the client")
    private String id;

    @Schema(description = "Group name, for example 'Field team'")
    private String name;

    @Schema(description = "Ids of the users that belong to the group")
    private List<String> userIds = new ArrayList<>();

    @Schema(description = "Ids of the RBAC roles assigned to every member of the group")
    private List<String> roleIds = new ArrayList<>();

}

