// SPDX-FileCopyrightText: Copyright The Thingsboard Authors
// SPDX-License-Identifier: Apache-2.0
package org.thingsboard.server.common.data.rbac;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.io.Serial;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Schema
@Data
public class RbacRole implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    @Schema(description = "Unique identifier of the role, generated by the client")
    private String id;

    @Schema(description = "Role name, for example 'Field technician'")
    private String name;

    @Schema(description = "Permissions by resource, for example { \"DEVICE\": [\"READ\", \"WRITE\"] }")
    private Map<String, List<String>> permissions = new HashMap<>();

    @Schema(description = "Group scoped permissions: { \"DEVICE\": { \"READ\": [\"group-id\"] } }. " +
            "Used to restrict an operation to the entities of the listed groups.")
    private Map<String, Map<String, List<String>>> scopedPermissions = new HashMap<>();

    @Schema(description = "Ids of users assigned to this role")
    private List<String> userIds = new ArrayList<>();

}
