// SPDX-FileCopyrightText: Copyright The Thingsboard Authors
// SPDX-License-Identifier: Apache-2.0
package org.thingsboard.server.common.data.menu;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.io.Serial;
import java.io.Serializable;

@Schema
@Data
public class CustomMenuItem implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    @Schema(description = "Unique identifier of the item, generated by the client")
    private String id;

    @Schema(description = "Display name of the menu item")
    private String name;

    @Schema(description = "Icon, for example mdi:view-dashboard-outline or a material icon name")
    private String icon;

    @Schema(description = "Link type: dashboard or url")
    private String type;

    @Schema(description = "Dashboard id (for dashboard type) or external url (for url type)")
    private String target;

    @Schema(description = "Who can see the item: TENANT_ADMIN or CUSTOMER_USER")
    private String assigneeType;

    @Schema(description = "Sort order")
    private Integer order;

}

