// SPDX-FileCopyrightText: Copyright The Thingsboard Authors
// SPDX-License-Identifier: Apache-2.0
package org.thingsboard.server.service.emulator;

import org.springframework.stereotype.Service;
import org.thingsboard.server.common.data.emulator.EmulatorProfile;
import org.thingsboard.server.common.data.emulator.EmulatorSignal;

import java.util.Arrays;
import java.util.List;
import java.util.Optional;

/**
 * Catalog of the virtual devices a tenant may create (like the Emulator Catalog of ThingsBoard PE).
 *
 * <p>Every profile describes a business domain, the telemetry keys it publishes with realistic units and ranges,
 * and the scenarios that change how the values move. The catalog is used to build demo dashboards for sales
 * (energy, agriculture, industrial, lighting, water, transportation, fleet, buildings, smart cities, cold chain,
 * environment, healthcare, retail, smart home, utilities), so the signals and the scenarios must look like the
 * real equipment of the domain: a solar inverter reports AC/DC power and efficiency, a cold room its temperature
 * and compressor state, a utility meter its volume and a monotonic reading, and so on.
 */
@Service
public class EmulatorCatalog {

    public static final String CATEGORY_ENERGY = "Energy";
    public static final String CATEGORY_AGRICULTURE = "Agriculture";
    public static final String CATEGORY_INDUSTRIAL = "Industrial";
    public static final String CATEGORY_LIGHTING = "Lighting";
    public static final String CATEGORY_WATER = "Water";
    public static final String CATEGORY_TRANSPORTATION = "Transportation";
    public static final String CATEGORY_FLEET = "Fleet";
    public static final String CATEGORY_BUILDINGS = "Buildings";
    public static final String CATEGORY_SMART_CITIES = "Smart Cities";
    public static final String CATEGORY_COLD_CHAIN = "Cold Chain";
    public static final String CATEGORY_ENVIRONMENT = "Environment";
    public static final String CATEGORY_HEALTHCARE = "Healthcare";
    public static final String CATEGORY_RETAIL = "Retail";
    public static final String CATEGORY_SMART_HOME = "Smart Home";
    public static final String CATEGORY_UTILITIES = "Utilities";

    private static final List<EmulatorProfile> PROFILES = List.of(

            // ======================================= Energy =======================================
            profile("solar-inverter-50kw", "Solar Inverter (50 kW)", CATEGORY_ENERGY, "Equipment", "ST-50K",
                    "Rooftop PV inverter: AC/DC power, produced energy, efficiency and cabinet temperature.",
                    "solar_power", "#305680", 10,
                    List.of("Sunny Afternoon", "Passing Clouds", "Failed String", "Grid Outage"), "Sunny Afternoon",
                    signal("acPower", "AC Power", "kW", EmulatorSignal.KIND_SINE, 0, 50, 2),
                    signal("dcPower", "DC Power", "kW", EmulatorSignal.KIND_SINE, 0, 52, 2),
                    counter("energy", "Total Energy", "kWh", 18450.35, 0.02, 2),
                    signal("efficiency", "Efficiency", "%", EmulatorSignal.KIND_SINE, 92, 98.5, 2),
                    signal("inverterTemp", "Inverter Temperature", "°C", EmulatorSignal.KIND_SINE, 28, 68, 1)),
            profile("smart-home-energy-hub", "Smart Home Energy Hub", CATEGORY_ENERGY, "System", "GATEWAY-ULTRA-X1",
                    "Home energy hub with solar, battery, grid backup and total load.",
                    "home_battery", "#305680", 10,
                    List.of("Typical Day", "Grid Blackout", "High Peak Demand"), "Typical Day",
                    signal("totalPower", "Total Power", "kW", EmulatorSignal.KIND_SINE, 0.2, 9.5, 2),
                    signal("homeLoad", "Home Load", "kW", EmulatorSignal.KIND_SINE, 0.3, 5.2, 2),
                    signal("solarPower", "Solar Power", "kW", EmulatorSignal.KIND_SINE, 0, 6.4, 2),
                    signal("batterySoc", "Battery SOC", "%", EmulatorSignal.KIND_RAMP, 15, 100, 0),
                    signal("gridStatus", "Grid Status", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Grid", "Backup")),
            profile("ev-charging-station", "EV Fast Charging Station", CATEGORY_ENERGY, "Equipment", "ULTRACHARGE-150",
                    "150 kW DC fast charger: session energy, cable lock and heat-based power reduction.",
                    "ev_station", "#305680", 10,
                    List.of("Ready For Charging", "EV Charging", "Thermal Throttling", "Fault"), "EV Charging",
                    signal("powerOutput", "Power Output", "kW", EmulatorSignal.KIND_SINE, 0, 150, 1),
                    counter("sessionEnergy", "Session Energy", "kWh", 0, 0.05, 2),
                    signal("temperature", "Charger Temperature", "°C", EmulatorSignal.KIND_SINE, 25, 78, 1),
                    signal("chargerState", "Charger State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Ready", "Charging", "Throttling", "Fault"),
                    signal("cableLock", "Cable Lock", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Locked", "Unlocked")),
            profile("wind-turbine-2mw", "Wind Turbine (2 MW)", CATEGORY_ENERGY, "System", "WT-2000",
                    "Onshore turbine: wind speed, produced power, rotor speed and pitch control.",
                    "wind_power", "#305680", 10,
                    List.of("Light Breeze", "Strong Wind", "Storm Cut-off", "Maintenance"), "Light Breeze",
                    signal("windSpeed", "Wind Speed", "m/s", EmulatorSignal.KIND_SINE, 2, 26, 1),
                    signal("power", "Active Power", "kW", EmulatorSignal.KIND_SINE, 0, 2000, 0),
                    signal("rotorSpeed", "Rotor Speed", "rpm", EmulatorSignal.KIND_SINE, 0, 18, 1),
                    signal("pitchAngle", "Pitch Angle", "°", EmulatorSignal.KIND_SINE, 0, 25, 1),
                    signal("turbineState", "Turbine State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Idle", "Generating", "Storm Cut-off", "Maintenance")),
            profile("battery-energy-storage", "Battery Energy Storage (BESS)", CATEGORY_ENERGY, "System", "BESS-500",
                    "Containerised battery: state of charge, charge/discharge power and cell temperature.",
                    "battery_charging_full", "#305680", 10,
                    List.of("Peak Shaving", "Night Charging", "Grid Support", "Maintenance"), "Peak Shaving",
                    signal("soc", "State Of Charge", "%", EmulatorSignal.KIND_RAMP, 10, 98, 1),
                    signal("power", "Power (+charge/-discharge)", "kW", EmulatorSignal.KIND_SINE, -250, 250, 1),
                    signal("voltage", "DC Voltage", "V", EmulatorSignal.KIND_SINE, 720, 800, 1),
                    signal("cellTemperature", "Cell Temperature", "°C", EmulatorSignal.KIND_SINE, 20, 42, 1),
                    signal("batteryState", "Battery State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Charging", "Discharging", "Idle", "Standby")),

            // ===================================== Agriculture ====================================
            profile("greenhouse-system", "Greenhouse System", CATEGORY_AGRICULTURE, "System", "GROWMASTER-PRO",
                    "Greenhouse climate, soil moisture, CO2 and irrigation control.",
                    "agriculture", "#2e7d32", 10,
                    List.of("Sunny Day", "Cloudy Day", "Heat Wave", "Rainy Day"), "Sunny Day",
                    signal("airTemperature", "Air Temperature", "°C", EmulatorSignal.KIND_SINE, 18, 38, 1),
                    signal("airHumidity", "Air Humidity", "%", EmulatorSignal.KIND_SINE, 35, 95, 0),
                    signal("soilMoisture", "Soil Moisture", "%", EmulatorSignal.KIND_SINE, 20, 75, 0),
                    signal("co2", "CO2", "ppm", EmulatorSignal.KIND_SINE, 380, 1200, 0),
                    signal("irrigation", "Irrigation", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Off", "On")),
            profile("smart-irrigation-pump", "Smart Irrigation Pump", CATEGORY_AGRICULTURE, "Equipment", "PUMP-5HP",
                    "Irrigation pump with flow, pressure, motor current and water level.",
                    "water_pump", "#2e7d32", 10,
                    List.of("Irrigation Cycle", "Dry Field", "Pump Failure"), "Irrigation Cycle",
                    signal("flowRate", "Flow Rate", "m³/h", EmulatorSignal.KIND_SINE, 0, 42, 1),
                    signal("pressure", "Pressure", "bar", EmulatorSignal.KIND_SINE, 0.5, 4.5, 2),
                    signal("motorCurrent", "Motor Current", "A", EmulatorSignal.KIND_SINE, 4, 18, 1),
                    signal("waterLevel", "Water Level", "%", EmulatorSignal.KIND_RAMP, 10, 100, 0),
                    signal("pumpState", "Pump State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Off", "On")),
            profile("soil-moisture-sensor", "Soil Moisture Sensor", CATEGORY_AGRICULTURE, "Sensor", "SM-100",
                    "Field sensor: soil moisture, temperature, conductivity and battery.",
                    "sensors", "#2e7d32", 30,
                    List.of("Dry Soil", "Irrigated", "After Rain"), "Irrigated",
                    signal("soilMoisture", "Soil Moisture", "%", EmulatorSignal.KIND_SINE, 12, 80, 0),
                    signal("soilTemperature", "Soil Temperature", "°C", EmulatorSignal.KIND_SINE, 15, 34, 1),
                    signal("soilConductivity", "Soil Conductivity", "mS/cm", EmulatorSignal.KIND_SINE, 0.2, 2.4, 2),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 20, 100, 0)),
            profile("weather-station", "Weather Station", CATEGORY_AGRICULTURE, "Sensor", "WS-2000",
                    "Field weather station: rain, wind, solar radiation and battery level.",
                    "cloud", "#2e7d32", 30,
                    List.of("Sunny", "Rainy", "Windy", "Storm"), "Sunny",
                    signal("airTemperature", "Air Temperature", "°C", EmulatorSignal.KIND_SINE, 12, 38, 1),
                    signal("airHumidity", "Air Humidity", "%", EmulatorSignal.KIND_SINE, 30, 98, 0),
                    signal("rainfall", "Rainfall", "mm", EmulatorSignal.KIND_RAMP, 0, 40, 1),
                    signal("windSpeed", "Wind Speed", "m/s", EmulatorSignal.KIND_SINE, 0, 24, 1),
                    signal("solarRadiation", "Solar Radiation", "W/m²", EmulatorSignal.KIND_SINE, 0, 950, 0),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 20, 100, 0)),
            profile("livestock-tracker", "Livestock Tracker", CATEGORY_AGRICULTURE, "Sensor", "LIVESTOCK-TRK",
                    "Animal collar: body temperature, activity, rumination and geo-zone.",
                    "pets", "#2e7d32", 30,
                    List.of("Grazing", "Resting", "Heat Stress", "Out Of Zone"), "Grazing",
                    signal("bodyTemperature", "Body Temperature", "°C", EmulatorSignal.KIND_SINE, 37, 40.5, 1),
                    signal("activityIndex", "Activity Index", "", EmulatorSignal.KIND_SINE, 0, 100, 0),
                    signal("ruminationMinutes", "Rumination", "min", EmulatorSignal.KIND_SINE, 0, 600, 0),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 25, 100, 0),
                    signal("geoZone", "Geo Zone", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Pasture", "Barn", "Watering", "Out Of Range")),

            // ===================================== Industrial =====================================
            profile("manufacturing-line-oee", "Manufacturing Line - OEE", CATEGORY_INDUSTRIAL, "System", "PKG-4200",
                    "Production line with availability, performance, quality and produced pieces.",
                    "precision_manufacturing", "#6d4c41", 10,
                    List.of("Normal Run", "Changeover", "Breakdown", "Planned Maintenance"), "Normal Run",
                    signal("availability", "Availability", "%", EmulatorSignal.KIND_SINE, 55, 99, 1),
                    signal("performance", "Performance", "%", EmulatorSignal.KIND_SINE, 60, 100, 1),
                    signal("quality", "Quality", "%", EmulatorSignal.KIND_SINE, 88, 100, 1),
                    signal("oee", "OEE", "%", EmulatorSignal.KIND_SINE, 45, 95, 1),
                    counter("outputCount", "Output Count", "pcs", 18450, 1, 0)),
            profile("air-compressor", "Air Compressor", CATEGORY_INDUSTRIAL, "Equipment", "AC-75",
                    "Compressed air station with pressure, temperature, vibration and running state.",
                    "settings_input_component", "#6d4c41", 10,
                    List.of("Load", "Unload", "Overheat", "Maintenance"), "Load",
                    signal("pressure", "Pressure", "bar", EmulatorSignal.KIND_SINE, 5.5, 8.5, 2),
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 45, 95, 1),
                    signal("vibration", "Vibration", "mm/s", EmulatorSignal.KIND_RANDOM, 0.4, 6.5, 2),
                    signal("running", "Running", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Off", "On"),
                    counter("energy", "Energy", "kWh", 22104.6, 0.01, 2)),
            profile("energy-meter-3phase", "Three Phase Energy Meter", CATEGORY_INDUSTRIAL, "Equipment", "EM-3P",
                    "Industrial meter: phase voltages, current, active power and power factor.",
                    "electric_meter", "#6d4c41", 10,
                    List.of("Balanced Load", "Phase Loss", "Peak Load"), "Balanced Load",
                    signal("voltageA", "Voltage L1", "V", EmulatorSignal.KIND_SINE, 215, 235, 1),
                    signal("voltageB", "Voltage L2", "V", EmulatorSignal.KIND_SINE, 215, 235, 1),
                    signal("voltageC", "Voltage L3", "V", EmulatorSignal.KIND_SINE, 215, 235, 1),
                    signal("currentA", "Current L1", "A", EmulatorSignal.KIND_SINE, 5, 120, 1),
                    signal("activePower", "Active Power", "kW", EmulatorSignal.KIND_SINE, 1, 75, 2),
                    signal("powerFactor", "Power Factor", "", EmulatorSignal.KIND_SINE, 0.75, 1, 2)),
            profile("cnc-machine", "CNC Machine", CATEGORY_INDUSTRIAL, "Equipment", "CNC-840D",
                    "Machining centre with spindle, feed, tool wear and machine state.",
                    "construction", "#6d4c41", 10,
                    List.of("Idle", "Cutting", "Tool Change", "Alarm"), "Cutting",
                    signal("spindleSpeed", "Spindle Speed", "rpm", EmulatorSignal.KIND_SINE, 0, 12000, 0),
                    signal("feedRate", "Feed Rate", "mm/min", EmulatorSignal.KIND_SINE, 0, 3000, 0),
                    signal("vibration", "Vibration", "mm/s", EmulatorSignal.KIND_RANDOM, 0.2, 8, 2),
                    signal("toolWear", "Tool Wear", "%", EmulatorSignal.KIND_RAMP, 0, 100, 0),
                    counter("parts", "Machined Parts", "pcs", 5120, 0.5, 0),
                    signal("machineState", "Machine State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Idle", "Cutting", "Tool Change", "Alarm")),
            profile("industrial-robot-arm", "Industrial Robot Arm", CATEGORY_INDUSTRIAL, "Equipment", "ARM-6AXIS",
                    "Six axis robot: cycle time, joint temperature, payload and vibration.",
                    "smart_toy", "#6d4c41", 10,
                    List.of("Production Run", "Slow Cycle", "Fault", "Maintenance"), "Production Run",
                    signal("cycleTime", "Cycle Time", "s", EmulatorSignal.KIND_SINE, 8, 22, 2),
                    signal("jointTemperature", "Joint Temperature", "°C", EmulatorSignal.KIND_SINE, 32, 68, 1),
                    signal("payload", "Payload", "kg", EmulatorSignal.KIND_SINE, 0, 12, 2),
                    signal("vibration", "Vibration", "mm/s", EmulatorSignal.KIND_RANDOM, 0.1, 4.5, 2),
                    signal("robotState", "Robot State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Running", "Idle", "Fault", "Maintenance")),

            // ====================================== Lighting ======================================
            profile("smart-street-light", "Smart Street Light", CATEGORY_LIGHTING, "Equipment", "SL-120",
                    "Street light with brightness control, lux measurement and lamp diagnostics.",
                    "lightbulb", "#f9a825", 10,
                    List.of("Evening", "Night Dimming", "Daylight", "Lamp Failure"), "Evening",
                    signal("lux", "Illuminance", "lx", EmulatorSignal.KIND_SINE, 0, 32000, 0),
                    signal("brightness", "Brightness", "%", EmulatorSignal.KIND_SINE, 0, 100, 0),
                    signal("power", "Power", "W", EmulatorSignal.KIND_SINE, 0, 120, 1),
                    signal("lampState", "Lamp State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Off", "On", "Dimmed", "Fault"),
                    counter("energy", "Energy", "kWh", 415.8, 0.005, 3)),
            profile("street-lighting-cabinet", "Street Lighting Cabinet", CATEGORY_LIGHTING, "System", "LC-240",
                    "Lighting cabinet: total power, active lamps, cabinet health and door state.",
                    "electrical_services", "#f9a825", 10,
                    List.of("Sunset On", "Midnight Dimming", "Sunrise Off", "Cabinet Overheat"), "Sunset On",
                    signal("totalPower", "Total Power", "kW", EmulatorSignal.KIND_SINE, 0, 18, 2),
                    signal("activeLamps", "Active Lamps", "pcs", EmulatorSignal.KIND_SINE, 0, 240, 0),
                    signal("cabinetTemperature", "Cabinet Temperature", "°C", EmulatorSignal.KIND_SINE, 22, 65, 1),
                    signal("doorState", "Door State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Closed", "Open"),
                    counter("energy", "Energy", "kWh", 8620.4, 0.02, 2)),
            profile("indoor-lighting-zone", "Indoor Lighting Zone", CATEGORY_LIGHTING, "System", "INDOOR-LZ",
                    "Indoor lighting zone with occupancy based dimming and energy metering.",
                    "light_mode", "#f9a825", 10,
                    List.of("Day", "Evening", "Night", "Off"), "Evening",
                    signal("brightness", "Brightness", "%", EmulatorSignal.KIND_SINE, 0, 100, 0),
                    signal("occupancy", "Occupancy", "pcs", EmulatorSignal.KIND_SINE, 0, 40, 0),
                    signal("power", "Power", "W", EmulatorSignal.KIND_SINE, 0, 600, 1),
                    signal("zoneState", "Zone State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Day", "Evening", "Night", "Off"),
                    counter("energy", "Energy", "kWh", 1240.6, 0.01, 2)),
            profile("stadium-floodlight", "Stadium Floodlight", CATEGORY_LIGHTING, "Equipment", "FLOOD-2000",
                    "Stadium floodlight with warm-up, tilt angle and lamp diagnostics.",
                    "wb_twilight", "#f9a825", 10,
                    List.of("Off", "Warm-up", "Match Mode", "Lamp Fault"), "Match Mode",
                    signal("power", "Power", "kW", EmulatorSignal.KIND_SINE, 0, 2, 2),
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 28, 75, 1),
                    signal("lux", "Illuminance", "lx", EmulatorSignal.KIND_SINE, 0, 2000, 0),
                    signal("tiltAngle", "Tilt Angle", "°", EmulatorSignal.KIND_SINE, 0, 35, 1),
                    signal("lampState", "Lamp State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Off", "Warm-up", "On", "Fault")),
            profile("solar-garden-light", "Solar Garden Light", CATEGORY_LIGHTING, "Equipment", "SGL-30",
                    "Solar garden light: battery, panel voltage, lux and lamp state.",
                    "solar_power", "#f9a825", 30,
                    List.of("Charging", "Evening On", "Night Dimming", "Battery Empty"), "Evening On",
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 5, 100, 0),
                    signal("panelVoltage", "Panel Voltage", "V", EmulatorSignal.KIND_SINE, 0, 18, 2),
                    signal("lux", "Illuminance", "lx", EmulatorSignal.KIND_SINE, 0, 80000, 0),
                    signal("power", "Power", "W", EmulatorSignal.KIND_SINE, 0, 30, 1),
                    signal("lampState", "Lamp State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Charging", "On", "Dimmed", "Off")),

            // ======================================= Water ========================================
            profile("water-tank-monitor", "Water Tank Monitor", CATEGORY_WATER, "Sensor", "WT-500",
                    "Municipal water tank: level, volume, pH, turbidity and battery.",
                    "water_drop", "#0288d1", 15,
                    List.of("Filling", "Consumption", "Low Level", "Maintenance"), "Consumption",
                    signal("level", "Water Level", "%", EmulatorSignal.KIND_RAMP, 5, 100, 0),
                    signal("volume", "Volume", "m³", EmulatorSignal.KIND_SINE, 0, 500, 1),
                    signal("ph", "pH", "", EmulatorSignal.KIND_SINE, 6.2, 8.4, 2),
                    signal("turbidity", "Turbidity", "NTU", EmulatorSignal.KIND_RANDOM, 0.1, 6, 2),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 25, 100, 0)),
            profile("water-treatment-plant", "Water Treatment Plant", CATEGORY_WATER, "System", "WTP-1000",
                    "Treatment plant with flow, chlorine dosing, pH and turbidity.",
                    "water", "#0288d1", 10,
                    List.of("Normal Operation", "High Demand", "Chlorine Low", "Pump Failure"), "Normal Operation",
                    signal("flowRate", "Flow Rate", "m³/h", EmulatorSignal.KIND_SINE, 10, 420, 0),
                    signal("chlorine", "Chlorine", "mg/l", EmulatorSignal.KIND_SINE, 0.2, 1.2, 2),
                    signal("ph", "pH", "", EmulatorSignal.KIND_SINE, 6.5, 8.2, 2),
                    signal("turbidity", "Turbidity", "NTU", EmulatorSignal.KIND_RANDOM, 0.05, 4, 2),
                    signal("pumpState", "Pump State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Off", "On")),
            profile("water-pump-station", "Water Pump Station", CATEGORY_WATER, "System", "WPS-300",
                    "Booster pump station: flow, discharge pressure, motor current and vibration.",
                    "plumbing", "#0288d1", 10,
                    List.of("Normal Supply", "Peak Demand", "Dry Run", "Pump Failure"), "Normal Supply",
                    signal("flowRate", "Flow Rate", "m³/h", EmulatorSignal.KIND_SINE, 0, 300, 1),
                    signal("pressure", "Discharge Pressure", "bar", EmulatorSignal.KIND_SINE, 2, 6.5, 2),
                    signal("motorCurrent", "Motor Current", "A", EmulatorSignal.KIND_SINE, 8, 64, 1),
                    signal("vibration", "Vibration", "mm/s", EmulatorSignal.KIND_RANDOM, 0.3, 5.5, 2),
                    signal("pumpState", "Pump State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Off", "Running", "Dry Run", "Fault")),
            profile("water-quality-sensor", "Water Quality Sensor", CATEGORY_WATER, "Sensor", "WQS-50",
                    "Inline water quality probe: pH, turbidity, chlorine and conductivity.",
                    "science", "#0288d1", 30,
                    List.of("Clean Water", "Turbidity Event", "Chlorine Low", "Sensor Fault"), "Clean Water",
                    signal("ph", "pH", "", EmulatorSignal.KIND_SINE, 6.3, 8.3, 2),
                    signal("turbidity", "Turbidity", "NTU", EmulatorSignal.KIND_RANDOM, 0.05, 5, 2),
                    signal("chlorine", "Chlorine", "mg/l", EmulatorSignal.KIND_SINE, 0.1, 1.1, 2),
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 8, 30, 1),
                    signal("conductivity", "Conductivity", "µS/cm", EmulatorSignal.KIND_SINE, 120, 850, 0),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 30, 100, 0)),
            profile("water-leak-detector", "Water Leak Detector", CATEGORY_WATER, "Sensor", "LEAK-10",
                    "Leak detection on a pipe: flow, pressure, moisture and valve state.",
                    "plumbing", "#0288d1", 15,
                    List.of("Dry", "Leak Detected", "Valve Closed", "Sensor Fault"), "Dry",
                    signal("flowRate", "Flow Rate", "l/h", EmulatorSignal.KIND_SINE, 0, 12, 2),
                    signal("pressure", "Pressure", "bar", EmulatorSignal.KIND_SINE, 1.5, 5.5, 2),
                    signal("moisture", "Moisture", "%", EmulatorSignal.KIND_SINE, 0, 100, 0),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 25, 100, 0),
                    signal("leakState", "Leak State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Dry", "Leak Detected", "Valve Closed")),

            // =================================== Transportation ===================================
            profile("refrigerated-truck", "Refrigerated Delivery Truck", CATEGORY_TRANSPORTATION, "System",
                    "TRACKERPRO-MAX",
                    "Cool chain truck: speed, engine, cargo temperature and door state.",
                    "local_shipping", "#455a64", 5,
                    List.of("On Route", "Traffic Jam", "Engine Idling", "Cooling Failure"), "On Route",
                    signal("speed", "Speed", "km/h", EmulatorSignal.KIND_SINE, 0, 95, 1),
                    signal("engineRpm", "Engine RPM", "rpm", EmulatorSignal.KIND_SINE, 700, 2600, 0),
                    signal("cargoTemp", "Cargo Temperature", "°C", EmulatorSignal.KIND_SINE, -22, 8, 1),
                    signal("fuelLevel", "Fuel Level", "%", EmulatorSignal.KIND_RAMP, 5, 100, 0),
                    signal("doorState", "Door State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Closed", "Open")),
            profile("cargo-trailer", "Cargo Trailer", CATEGORY_TRANSPORTATION, "System", "TRAILER-X1",
                    "Trailer telematics: load, tyre pressure, brake state and door.",
                    "rv_hookup", "#455a64", 15,
                    List.of("Loaded", "Empty", "Door Open", "Brake Issue"), "Loaded",
                    signal("cargoWeight", "Cargo Weight", "kg", EmulatorSignal.KIND_SINE, 2000, 24000, 0),
                    signal("temperature", "Cargo Temperature", "°C", EmulatorSignal.KIND_SINE, -5, 30, 1),
                    signal("tirePressure", "Tyre Pressure", "bar", EmulatorSignal.KIND_SINE, 7.2, 8.6, 1),
                    signal("doorState", "Door State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Closed", "Open"),
                    signal("brakeState", "Brake State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Released", "Applied")),
            profile("cold-chain-container", "Cold Chain Container (Reefer)", CATEGORY_TRANSPORTATION, "System",
                    "REEFER-40",
                    "Reefer container with temperature, set point and refrigeration state.",
                    "ac_unit", "#455a64", 10,
                    List.of("Cooling", "Defrost", "Standby", "Power Loss"), "Cooling",
                    signal("temperature", "Container Temperature", "°C", EmulatorSignal.KIND_SINE, -25, -12, 1),
                    signal("setPoint", "Set Point", "°C", EmulatorSignal.KIND_SINE, -25, -10, 1),
                    signal("humidity", "Humidity", "%", EmulatorSignal.KIND_SINE, 55, 95, 0),
                    signal("power", "Power", "kW", EmulatorSignal.KIND_SINE, 0.5, 9, 2),
                    signal("reeferState", "Reefer State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Cooling", "Defrost", "Standby", "Fault")),
            profile("public-bus-tracker", "Public Bus Tracker", CATEGORY_TRANSPORTATION, "System", "BUS-TRK-500",
                    "City bus: speed, passengers, fuel, odometer and doors.",
                    "directions_bus", "#455a64", 10,
                    List.of("In Service", "At Stop", "Rush Hour", "Depot"), "In Service",
                    signal("speed", "Speed", "km/h", EmulatorSignal.KIND_SINE, 0, 70, 1),
                    signal("passengers", "Passengers", "pcs", EmulatorSignal.KIND_SINE, 0, 70, 0),
                    signal("fuelLevel", "Fuel Level", "%", EmulatorSignal.KIND_RAMP, 10, 100, 0),
                    counter("odometer", "Odometer", "km", 128430.5, 0.02, 1),
                    signal("doorState", "Door State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Closed", "Open")),
            profile("rail-wagon-monitor", "Rail Wagon Monitor", CATEGORY_TRANSPORTATION, "Sensor", "RAIL-WM",
                    "Wagon telemetry: speed, axle temperature, load and brake pressure.",
                    "train", "#455a64", 15,
                    List.of("In Transit", "Shunting", "Braking", "Hot Axle Alarm"), "In Transit",
                    signal("speed", "Speed", "km/h", EmulatorSignal.KIND_SINE, 0, 90, 1),
                    signal("axleTemperature", "Axle Temperature", "°C", EmulatorSignal.KIND_SINE, 25, 75, 1),
                    signal("load", "Load", "t", EmulatorSignal.KIND_SINE, 0, 60, 1),
                    signal("vibration", "Vibration", "mm/s", EmulatorSignal.KIND_RANDOM, 0.2, 6, 2),
                    signal("brakePressure", "Brake Pressure", "bar", EmulatorSignal.KIND_SINE, 3.5, 5.5, 2)),

            // ======================================= Fleet ========================================
            profile("fleet-vehicle-tracker", "Fleet Vehicle Tracker", CATEGORY_FLEET, "System", "FLEET-TRK",
                    "OBD tracker: speed, fuel, odometer and engine state.",
                    "directions_car", "#455a64", 10,
                    List.of("Parked", "City Drive", "Highway", "Engine Failure"), "City Drive",
                    signal("speed", "Speed", "km/h", EmulatorSignal.KIND_SINE, 0, 120, 0),
                    signal("fuelLevel", "Fuel Level", "%", EmulatorSignal.KIND_RAMP, 5, 100, 0),
                    counter("odometer", "Odometer", "km", 76320.5, 0.02, 1),
                    signal("engineState", "Engine State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Off", "Idle", "Driving", "Failure")),
            profile("fleet-fuel-sensor", "Fleet Fuel Sensor", CATEGORY_FLEET, "Sensor", "FUEL-SNS",
                    "Fuel level probe: level, consumption, tank temperature and water in fuel.",
                    "local_gas_station", "#455a64", 15,
                    List.of("Full Tank", "Normal Consumption", "Refuelling", "Fuel Theft"), "Normal Consumption",
                    signal("fuelLevel", "Fuel Level", "%", EmulatorSignal.KIND_RAMP, 5, 100, 0),
                    signal("consumption", "Consumption", "l/h", EmulatorSignal.KIND_SINE, 4, 28, 2),
                    signal("tankTemperature", "Tank Temperature", "°C", EmulatorSignal.KIND_SINE, 15, 45, 1),
                    signal("waterInFuel", "Water In Fuel", "%", EmulatorSignal.KIND_SINE, 0, 3, 2),
                    signal("sensorState", "Sensor State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Ok", "Low Fuel", "Water Detected", "Fault")),
            profile("fleet-tire-pressure", "Fleet Tire Pressure Monitor", CATEGORY_FLEET, "Sensor", "TPMS-4W",
                    "Tyre pressure monitor of a four wheel vehicle.",
                    "tire_repair", "#455a64", 30,
                    List.of("Normal", "Low Pressure", "High Temperature", "Sensor Fault"), "Normal",
                    signal("pressureFL", "Pressure Front Left", "bar", EmulatorSignal.KIND_SINE, 6.8, 8.8, 1),
                    signal("pressureFR", "Pressure Front Right", "bar", EmulatorSignal.KIND_SINE, 6.8, 8.8, 1),
                    signal("pressureRL", "Pressure Rear Left", "bar", EmulatorSignal.KIND_SINE, 6.8, 8.8, 1),
                    signal("pressureRR", "Pressure Rear Right", "bar", EmulatorSignal.KIND_SINE, 6.8, 8.8, 1),
                    signal("temperature", "Tyre Temperature", "°C", EmulatorSignal.KIND_SINE, 20, 75, 1),
                    signal("alarmState", "Alarm State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Normal", "Low Pressure", "High Temperature")),
            profile("fleet-dashcam-telemetry", "Fleet Dashcam Telemetry", CATEGORY_FLEET, "Equipment", "DASHCAM-1",
                    "Dashcam with driving events and a driver score for coaching reports.",
                    "videocam", "#455a64", 10,
                    List.of("Smooth Drive", "City Traffic", "Harsh Driving", "Incident"), "City Traffic",
                    signal("speed", "Speed", "km/h", EmulatorSignal.KIND_SINE, 0, 130, 0),
                    counter("harshBraking", "Harsh Braking Events", "pcs", 12, 0.02, 0),
                    counter("harshAcceleration", "Harsh Acceleration Events", "pcs", 7, 0.01, 0),
                    signal("speedLimit", "Speed Limit", "km/h", EmulatorSignal.KIND_SINE, 40, 80, 0),
                    signal("driverScore", "Driver Score", "", EmulatorSignal.KIND_SINE, 55, 99, 0)),
            profile("electric-fleet-van", "Electric Fleet Van", CATEGORY_FLEET, "System", "EVAN-350",
                    "Electric delivery van: state of charge, range, charging state and odometer.",
                    "electric_car", "#455a64", 10,
                    List.of("Depot Charging", "City Delivery", "Highway", "Low Battery"), "City Delivery",
                    signal("soc", "State Of Charge", "%", EmulatorSignal.KIND_RAMP, 8, 100, 1),
                    signal("range", "Estimated Range", "km", EmulatorSignal.KIND_SINE, 12, 310, 0),
                    signal("speed", "Speed", "km/h", EmulatorSignal.KIND_SINE, 0, 110, 0),
                    counter("odometer", "Odometer", "km", 41250.8, 0.02, 1),
                    signal("chargingState", "Charging State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Unplugged", "Charging", "Ready", "Fault")),

            // ===================================== Buildings ======================================
            profile("hvac-air-handling-unit", "HVAC Air Handling Unit", CATEGORY_BUILDINGS, "Equipment", "AHU-500",
                    "Air handling unit: supply/return temperature, fan speed and filter load.",
                    "ac_unit", "#00838f", 10,
                    List.of("Comfort", "Cooling Down", "Economy Mode", "Filter Clogged"), "Comfort",
                    signal("supplyTemperature", "Supply Temperature", "°C", EmulatorSignal.KIND_SINE, 12, 26, 1),
                    signal("returnTemperature", "Return Temperature", "°C", EmulatorSignal.KIND_SINE, 18, 30, 1),
                    signal("fanSpeed", "Fan Speed", "%", EmulatorSignal.KIND_SINE, 0, 100, 0),
                    signal("filterPressure", "Filter Pressure", "Pa", EmulatorSignal.KIND_RAMP, 40, 320, 0),
                    signal("running", "Running", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Off", "On")),
            profile("elevator", "Elevator", CATEGORY_BUILDINGS, "System", "ELEV-1000",
                    "Passenger elevator: floor, speed, load, doors and alarm.",
                    "elevator", "#00838f", 10,
                    List.of("Normal Service", "Rush Hour", "Maintenance", "Alarm"), "Normal Service",
                    signal("currentFloor", "Current Floor", "floor", EmulatorSignal.KIND_RAMP, 0, 20, 0),
                    signal("speed", "Speed", "m/s", EmulatorSignal.KIND_SINE, 0, 2.5, 2),
                    signal("load", "Load", "kg", EmulatorSignal.KIND_SINE, 0, 800, 0),
                    signal("doorState", "Door State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Closed", "Open"),
                    signal("alarm", "Alarm", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Off", "On")),
            profile("building-electricity-meter", "Building Electricity Meter", CATEGORY_BUILDINGS, "Equipment",
                    "B-EM-100",
                    "Building main meter: active power, energy, voltage, current and power factor.",
                    "electric_meter", "#00838f", 10,
                    List.of("Office Hours", "Night Load", "Peak Demand", "Power Event"), "Office Hours",
                    signal("activePower", "Active Power", "kW", EmulatorSignal.KIND_SINE, 15, 320, 1),
                    counter("energy", "Total Energy", "kWh", 486210.4, 0.05, 1),
                    signal("voltage", "Voltage", "V", EmulatorSignal.KIND_SINE, 218, 235, 1),
                    signal("current", "Current", "A", EmulatorSignal.KIND_SINE, 25, 480, 1),
                    signal("powerFactor", "Power Factor", "", EmulatorSignal.KIND_SINE, 0.85, 1, 2)),
            profile("fire-alarm-panel", "Fire Alarm Panel", CATEGORY_BUILDINGS, "System", "FIRE-P10",
                    "Fire panel with smoke level, temperature, battery and zone state.",
                    "local_fire_department", "#00838f", 10,
                    List.of("Normal", "Pre-Alarm", "Fire Alarm", "Battery Low"), "Normal",
                    signal("smokeLevel", "Smoke Level", "%/m", EmulatorSignal.KIND_SINE, 0, 35, 1),
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 18, 65, 1),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 40, 100, 0),
                    signal("alarmState", "Alarm State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Normal", "Pre-Alarm", "Alarm"),
                    signal("zoneState", "Zone State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Zone 1 Normal", "Zone 2 Normal", "Zone 3 Alarm")),
            profile("access-control-door", "Access Control Door", CATEGORY_BUILDINGS, "Equipment", "DOOR-AC-2",
                    "Access controlled door: openings, badge reads, tamper and door state.",
                    "door_front_door", "#00838f", 10,
                    List.of("Office Hours", "After Hours", "Tamper Attempt", "Door Left Open"), "Office Hours",
                    counter("openCount", "Openings", "pcs", 1284, 0.02, 0),
                    counter("badgeReads", "Badge Reads", "pcs", 5310, 0.05, 0),
                    signal("doorState", "Door State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Closed", "Open"),
                    signal("tamperState", "Tamper State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Normal", "Tamper"),
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 20, 32, 1)),

            // ==================================== Smart Cities ====================================
            profile("smart-parking-system", "Smart Parking System", CATEGORY_SMART_CITIES, "System", "ZONEMASTER-500",
                    "Parking zone: occupancy, free slots, air quality and gate state.",
                    "local_parking", "#5e35b1", 10,
                    List.of("Busy Hour", "Free Flow", "Full Capacity", "Gate Fault"), "Busy Hour",
                    signal("occupancy", "Occupancy", "%", EmulatorSignal.KIND_SINE, 5, 100, 0),
                    signal("freeSlots", "Free Slots", "pcs", EmulatorSignal.KIND_SINE, 0, 320, 0),
                    signal("airQuality", "Air Quality", "AQI", EmulatorSignal.KIND_SINE, 15, 180, 0),
                    signal("gateState", "Gate State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Closed", "Open")),
            profile("smart-waste-bin", "Smart Waste Bin", CATEGORY_SMART_CITIES, "Sensor", "BIN-100",
                    "Waste bin: fill level, odour, collections and lid state.",
                    "delete_outline", "#5e35b1", 30,
                    List.of("Empty", "Half Full", "Full", "Odour Alert"), "Half Full",
                    signal("fillLevel", "Fill Level", "%", EmulatorSignal.KIND_RAMP, 0, 100, 0),
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 18, 42, 1),
                    signal("odour", "Odour", "ppm", EmulatorSignal.KIND_RANDOM, 0, 60, 0),
                    counter("collections", "Collections", "pcs", 184, 0.02, 0),
                    signal("lidState", "Lid State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Closed", "Open")),
            profile("smart-bus-stop", "Smart Bus Stop", CATEGORY_SMART_CITIES, "System", "BUSSTOP-10",
                    "Bus stop with passenger count, display, air quality and power.",
                    "directions_bus", "#5e35b1", 15,
                    List.of("Off Peak", "Rush Hour", "Display Fault", "Night Mode"), "Rush Hour",
                    signal("waitingPassengers", "Waiting Passengers", "pcs", EmulatorSignal.KIND_SINE, 0, 40, 0),
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 20, 40, 1),
                    signal("airQuality", "Air Quality", "AQI", EmulatorSignal.KIND_SINE, 20, 170, 0),
                    signal("power", "Power", "W", EmulatorSignal.KIND_SINE, 20, 260, 1),
                    signal("displayState", "Display State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "On", "Dimmed", "Off", "Fault")),
            profile("city-noise-sensor", "City Noise Sensor", CATEGORY_SMART_CITIES, "Sensor", "NOISE-20",
                    "Noise monitoring for city reports: average and peak level.",
                    "volume_up", "#5e35b1", 30,
                    List.of("Quiet Night", "Day Traffic", "Rush Hour", "Construction"), "Day Traffic",
                    signal("noise", "Noise Level", "dB", EmulatorSignal.KIND_SINE, 35, 95, 1),
                    signal("peakNoise", "Peak Noise", "dB", EmulatorSignal.KIND_SINE, 60, 110, 1),
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 18, 40, 1),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 25, 100, 0),
                    signal("alertState", "Alert State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Quiet", "Moderate", "Loud", "Critical")),
            profile("smart-traffic-light", "Smart Traffic Light", CATEGORY_SMART_CITIES, "System", "TRAFFIC-L8",
                    "Traffic light with vehicle counting, congestion and phase state.",
                    "traffic", "#5e35b1", 10,
                    List.of("Normal Cycle", "Rush Hour", "Night Mode", "Detector Fault"), "Normal Cycle",
                    counter("vehicleCount", "Vehicle Count", "pcs", 18420, 1, 0),
                    signal("waitingTime", "Waiting Time", "s", EmulatorSignal.KIND_SINE, 5, 90, 0),
                    signal("congestion", "Congestion", "%", EmulatorSignal.KIND_SINE, 10, 95, 0),
                    signal("currentPhase", "Current Phase", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "North-South Green", "East-West Green", "All Red"),
                    signal("faultState", "Fault State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Ok", "Detector Fault", "Lamp Fault")),

            // ==================================== Cold Chain ======================================
            profile("cold-storage-room", "Cold Storage Room", CATEGORY_COLD_CHAIN, "System", "COLD-ROOM-1",
                    "Cold room: temperature, humidity, power and compressor state.",
                    "ac_unit", "#0277bd", 10,
                    List.of("Normal Storage", "Door Open", "Compressor Failure", "Defrost"), "Normal Storage",
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, -25, -5, 1),
                    signal("humidity", "Humidity", "%", EmulatorSignal.KIND_SINE, 60, 95, 0),
                    signal("power", "Power", "kW", EmulatorSignal.KIND_SINE, 0.5, 12, 2),
                    signal("doorState", "Door State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Closed", "Open"),
                    signal("compressorState", "Compressor", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Off", "Cooling", "Defrost", "Fault")),
            profile("refrigerated-container", "Refrigerated Container (Reefer)", CATEGORY_COLD_CHAIN, "System",
                    "REEFER-40",
                    "Reefer container of a cold chain shipment.",
                    "ac_unit", "#0277bd", 10,
                    List.of("Cooling", "Defrost", "Standby", "Fault"), "Cooling",
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, -25, -10, 1),
                    signal("setPoint", "Set Point", "°C", EmulatorSignal.KIND_SINE, -25, -10, 1),
                    signal("humidity", "Humidity", "%", EmulatorSignal.KIND_SINE, 55, 92, 0),
                    signal("power", "Power", "kW", EmulatorSignal.KIND_SINE, 0.5, 8.5, 2),
                    signal("reeferState", "Reefer State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Cooling", "Defrost", "Standby", "Fault")),
            profile("cold-chain-door-sensor", "Cold Chain Door Sensor", CATEGORY_COLD_CHAIN, "Sensor", "CC-DOOR",
                    "Door contact of a cold room: state, open duration and alarm.",
                    "sensor_door", "#0277bd", 15,
                    List.of("Closed", "Door Left Open", "Temperature Rise", "Sensor Fault"), "Closed",
                    signal("doorState", "Door State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Closed", "Open"),
                    signal("openDuration", "Open Duration", "s", EmulatorSignal.KIND_RAMP, 0, 600, 0),
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, -25, 5, 1),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 25, 100, 0),
                    signal("alarmState", "Alarm State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Normal", "Door Left Open")),
            profile("freezer-room", "Freezer Room", CATEGORY_COLD_CHAIN, "System", "FREEZER-1",
                    "Blast freezer: temperature, defrost cycle and compressor power.",
                    "ac_unit", "#0277bd", 10,
                    List.of("Freezing", "Defrost", "Door Open", "Compressor Fault"), "Freezing",
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, -30, -18, 1),
                    signal("humidity", "Humidity", "%", EmulatorSignal.KIND_SINE, 60, 95, 0),
                    signal("compressorPower", "Compressor Power", "kW", EmulatorSignal.KIND_SINE, 1, 9, 2),
                    signal("defrostState", "Defrost State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Off", "Defrosting"),
                    signal("doorState", "Door State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Closed", "Open")),
            profile("vaccine-cold-box", "Vaccine Cold Box", CATEGORY_COLD_CHAIN, "Sensor", "VACC-BOX",
                    "Vaccine carrier box: inside/ambient temperature, lid and excursion alarm.",
                    "vaccines", "#0277bd", 15,
                    List.of("Normal", "Lid Open", "Heat Alert", "Power Loss"), "Normal",
                    signal("temperature", "Inside Temperature", "°C", EmulatorSignal.KIND_SINE, 2, 10, 1),
                    signal("ambientTemperature", "Ambient Temperature", "°C", EmulatorSignal.KIND_SINE, 22, 38, 1),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 30, 100, 0),
                    signal("lidState", "Lid State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Closed", "Open"),
                    signal("alarmState", "Alarm State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Normal", "Temperature Excursion")),

            // ==================================== Environment ====================================
            profile("air-quality-station", "Air Quality Station", CATEGORY_ENVIRONMENT, "Sensor", "AQ-300",
                    "Urban air quality: particulates, CO2, noise and weather.",
                    "air", "#00796b", 30,
                    List.of("Clean Air", "Rush Hour", "Wildfire Smoke", "Rain"), "Rush Hour",
                    signal("pm25", "PM2.5", "µg/m³", EmulatorSignal.KIND_SINE, 2, 180, 1),
                    signal("pm10", "PM10", "µg/m³", EmulatorSignal.KIND_SINE, 5, 260, 1),
                    signal("co2", "CO2", "ppm", EmulatorSignal.KIND_SINE, 380, 1400, 0),
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 12, 38, 1),
                    signal("humidity", "Humidity", "%", EmulatorSignal.KIND_SINE, 25, 95, 0),
                    signal("noise", "Noise", "dB", EmulatorSignal.KIND_SINE, 30, 95, 1)),
            profile("river-level-sensor", "River Level Sensor", CATEGORY_ENVIRONMENT, "Sensor", "RIVER-L",
                    "River monitoring: level, flow, rain and flood warning state.",
                    "waves", "#00796b", 30,
                    List.of("Normal", "Heavy Rain", "Flood Watch", "Flood Warning"), "Normal",
                    signal("level", "Water Level", "m", EmulatorSignal.KIND_SINE, 0.5, 6.5, 2),
                    signal("flowRate", "Flow Rate", "m³/s", EmulatorSignal.KIND_SINE, 2, 180, 1),
                    signal("rainfall", "Rainfall", "mm", EmulatorSignal.KIND_RAMP, 0, 80, 1),
                    signal("temperature", "Water Temperature", "°C", EmulatorSignal.KIND_SINE, 12, 30, 1),
                    signal("floodState", "Flood State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Normal", "Watch", "Warning", "Critical")),
            profile("solar-radiation-sensor", "Solar Radiation Sensor", CATEGORY_ENVIRONMENT, "Sensor", "SOLAR-RAD",
                    "Pyranometer for solar reports: irradiance, module and air temperature.",
                    "wb_sunny", "#00796b", 30,
                    List.of("Clear Sky", "Partly Cloudy", "Overcast", "Storm"), "Clear Sky",
                    signal("irradiance", "Irradiance", "W/m²", EmulatorSignal.KIND_SINE, 0, 1100, 0),
                    signal("moduleTemperature", "Module Temperature", "°C", EmulatorSignal.KIND_SINE, 15, 62, 1),
                    signal("airTemperature", "Air Temperature", "°C", EmulatorSignal.KIND_SINE, 10, 40, 1),
                    signal("humidity", "Humidity", "%", EmulatorSignal.KIND_SINE, 20, 95, 0),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 30, 100, 0)),
            profile("water-quality-buoy", "Water Quality Buoy", CATEGORY_ENVIRONMENT, "Sensor", "WQ-BUOY",
                    "Floating buoy: pH, dissolved oxygen, turbidity and battery.",
                    "sailing", "#00796b", 30,
                    List.of("Clean Lake", "Algae Bloom", "After Storm", "Low Battery"), "Clean Lake",
                    signal("ph", "pH", "", EmulatorSignal.KIND_SINE, 6, 8.8, 2),
                    signal("dissolvedOxygen", "Dissolved Oxygen", "mg/l", EmulatorSignal.KIND_SINE, 4, 11, 2),
                    signal("turbidity", "Turbidity", "NTU", EmulatorSignal.KIND_RANDOM, 0.2, 12, 2),
                    signal("temperature", "Water Temperature", "°C", EmulatorSignal.KIND_SINE, 12, 32, 1),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 20, 100, 0)),
            profile("rain-gauge", "Rain Gauge", CATEGORY_ENVIRONMENT, "Sensor", "RAIN-G",
                    "Tipping bucket rain gauge with intensity and storm alert.",
                    "water_drop", "#00796b", 30,
                    List.of("Dry", "Light Rain", "Heavy Rain", "Storm"), "Light Rain",
                    signal("rainfall", "Rainfall", "mm", EmulatorSignal.KIND_RAMP, 0, 60, 1),
                    signal("intensity", "Rain Intensity", "mm/h", EmulatorSignal.KIND_SINE, 0, 45, 1),
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 12, 38, 1),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 25, 100, 0),
                    signal("alertState", "Alert State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Dry", "Light Rain", "Heavy Rain", "Storm")),

            // ==================================== Healthcare =====================================
            profile("medical-refrigerator", "Medical Refrigerator", CATEGORY_HEALTHCARE, "Equipment", "MEDFRIDGE-2",
                    "Vaccine refrigerator with temperature, door, battery and excursion alarm.",
                    "vaccines", "#c2185b", 10,
                    List.of("Normal", "Door Open", "Power Outage", "Temperature Excursion"), "Normal",
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 2, 12, 1),
                    signal("humidity", "Humidity", "%", EmulatorSignal.KIND_SINE, 35, 75, 0),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 30, 100, 0),
                    signal("doorState", "Door State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Closed", "Open"),
                    signal("alarmState", "Alarm State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Normal", "Door Alarm", "Temperature Alarm")),
            profile("patient-vitals-monitor", "Patient Vitals Monitor", CATEGORY_HEALTHCARE, "Equipment", "VITALS-M1",
                    "Bedside monitor: heart rate, SpO2, temperature and blood pressure.",
                    "monitor_heart", "#c2185b", 10,
                    List.of("Stable", "Exercise", "Fever", "Critical"), "Stable",
                    signal("heartRate", "Heart Rate", "bpm", EmulatorSignal.KIND_SINE, 55, 110, 0),
                    signal("spo2", "SpO2", "%", EmulatorSignal.KIND_SINE, 92, 100, 0),
                    signal("bodyTemperature", "Body Temperature", "°C", EmulatorSignal.KIND_SINE, 36, 39, 1),
                    signal("systolic", "Blood Pressure Systolic", "mmHg", EmulatorSignal.KIND_SINE, 100, 145, 0),
                    signal("diastolic", "Blood Pressure Diastolic", "mmHg", EmulatorSignal.KIND_SINE, 60, 95, 0)),
            profile("infusion-pump", "Infusion Pump", CATEGORY_HEALTHCARE, "Equipment", "INFUSION-P2",
                    "Infusion pump: flow rate, remaining volume, occlusion and battery.",
                    "medication", "#c2185b", 10,
                    List.of("Idle", "Infusing", "Paused", "Occlusion Alarm"), "Infusing",
                    signal("flowRate", "Flow Rate", "ml/h", EmulatorSignal.KIND_SINE, 5, 120, 0),
                    signal("remainingVolume", "Remaining Volume", "ml", EmulatorSignal.KIND_RAMP, 20, 480, 0),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 20, 100, 0),
                    signal("occlusionState", "Occlusion State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Clear", "Occlusion", "Alarm"),
                    signal("infusionState", "Infusion State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Idle", "Infusing", "Paused", "Complete")),
            profile("hospital-bed-sensor", "Hospital Bed Sensor", CATEGORY_HEALTHCARE, "Equipment", "BED-S1",
                    "Smart bed: occupancy, patient weight, backrest angle and nurse call.",
                    "bedtime", "#c2185b", 10,
                    List.of("Empty", "Occupied", "Nurse Call", "Emergency Call"), "Occupied",
                    signal("weight", "Patient Weight", "kg", EmulatorSignal.KIND_SINE, 45, 120, 1),
                    signal("bedAngle", "Backrest Angle", "°", EmulatorSignal.KIND_SINE, 0, 60, 0),
                    signal("motion", "Motion", "%", EmulatorSignal.KIND_SINE, 0, 100, 0),
                    signal("occupancy", "Occupancy", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Empty", "Occupied"),
                    signal("callState", "Call State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "None", "Nurse Call", "Emergency")),
            profile("steam-sterilizer", "Steam Sterilizer", CATEGORY_HEALTHCARE, "Equipment", "STERIL-100",
                    "Autoclave: chamber temperature, pressure, cycle time and door.",
                    "sanitizer", "#c2185b", 10,
                    List.of("Idle", "Heating", "Sterilizing", "Drying", "Fault"), "Sterilizing",
                    signal("temperature", "Chamber Temperature", "°C", EmulatorSignal.KIND_SINE, 20, 134, 1),
                    signal("pressure", "Chamber Pressure", "bar", EmulatorSignal.KIND_SINE, 0, 2.1, 2),
                    signal("cycleTime", "Cycle Time", "s", EmulatorSignal.KIND_RAMP, 0, 2700, 0),
                    signal("doorState", "Door State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Closed", "Open"),
                    signal("cycleState", "Cycle State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Idle", "Heating", "Sterilizing", "Drying")),

            // ====================================== Retail =======================================
            profile("vending-machine", "Vending Machine", CATEGORY_RETAIL, "Equipment", "CHILLVEND-500",
                    "Connected vending machine: sales, stock, temperature and door.",
                    "storefront", "#ef6c00", 10,
                    List.of("Normal Sales", "High Demand", "Out Of Stock", "Door Open"), "Normal Sales",
                    signal("sales", "Sales", "pcs", EmulatorSignal.KIND_SINE, 0, 25, 0),
                    counter("totalSales", "Total Sales", "pcs", 8420, 1, 0),
                    signal("stock", "Stock", "%", EmulatorSignal.KIND_RAMP, 5, 100, 0),
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 2, 10, 1),
                    signal("doorState", "Door State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Closed", "Open")),
            profile("shelf-weight-sensor", "Shelf Weight Sensor", CATEGORY_RETAIL, "Sensor", "SHELF-W1",
                    "Smart shelf: weight, stock level, temperature and restock state.",
                    "scale", "#ef6c00", 30,
                    List.of("Full Shelf", "Selling", "Low Stock", "Out Of Stock"), "Selling",
                    signal("weight", "Weight", "kg", EmulatorSignal.KIND_SINE, 0, 45, 2),
                    signal("stockLevel", "Stock Level", "%", EmulatorSignal.KIND_RAMP, 5, 100, 0),
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 18, 28, 1),
                    signal("humidity", "Humidity", "%", EmulatorSignal.KIND_SINE, 35, 70, 0),
                    signal("restockState", "Restock State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Ok", "Low Stock", "Out Of Stock")),
            profile("retail-room-climate", "Retail Room Climate", CATEGORY_RETAIL, "System", "RETAIL-CLIM",
                    "Store climate: temperature, humidity, CO2, HVAC state and power.",
                    "thermostat", "#ef6c00", 10,
                    List.of("Comfort", "Rush Hour", "Closing Time", "HVAC Fault"), "Comfort",
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 19, 27, 1),
                    signal("humidity", "Humidity", "%", EmulatorSignal.KIND_SINE, 35, 70, 0),
                    signal("co2", "CO2", "ppm", EmulatorSignal.KIND_SINE, 400, 1200, 0),
                    signal("power", "HVAC Power", "kW", EmulatorSignal.KIND_SINE, 2, 24, 1),
                    signal("hvacState", "HVAC State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Idle", "Cooling", "Heating")),
            profile("self-checkout-counter", "Self Checkout Counter", CATEGORY_RETAIL, "Equipment", "SCO-4",
                    "Self checkout: transactions, queue length, scan time and scanner state.",
                    "point_of_sale", "#ef6c00", 10,
                    List.of("Normal Flow", "Peak Hour", "Scanner Cleaning Needed", "Fault"), "Normal Flow",
                    counter("transactions", "Transactions", "pcs", 12680, 1, 0),
                    signal("queueLength", "Queue Length", "pcs", EmulatorSignal.KIND_SINE, 0, 8, 0),
                    signal("avgTransactionTime", "Average Transaction Time", "s", EmulatorSignal.KIND_SINE, 25, 120, 0),
                    signal("scannerState", "Scanner State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Ok", "Cleaning Needed", "Fault"),
                    signal("powerState", "Power State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "On", "Sleep")),
            profile("coffee-machine", "Coffee Machine", CATEGORY_RETAIL, "Equipment", "COFFEE-X1",
                    "Connected coffee machine: cups served, water, beans and boiler temperature.",
                    "coffee", "#ef6c00", 10,
                    List.of("Ready", "Brewing", "Descale Needed", "Fault"), "Brewing",
                    counter("cupsServed", "Cups Served", "pcs", 3240, 1, 0),
                    signal("waterLevel", "Water Level", "%", EmulatorSignal.KIND_RAMP, 10, 100, 0),
                    signal("beanLevel", "Bean Level", "%", EmulatorSignal.KIND_RAMP, 5, 100, 0),
                    signal("boilerTemperature", "Boiler Temperature", "°C", EmulatorSignal.KIND_SINE, 85, 96, 1),
                    signal("machineState", "Machine State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Ready", "Brewing", "Descale Needed", "Fault")),

            // ==================================== Smart Home =====================================
            profile("smart-thermostat", "Smart Thermostat", CATEGORY_SMART_HOME, "Equipment", "THERMO-S2",
                    "Room thermostat with target temperature, HVAC state and occupancy.",
                    "thermostat", "#00897b", 10,
                    List.of("Comfort", "Eco Mode", "Away", "Heat Wave"), "Comfort",
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 15, 35, 1),
                    signal("targetTemperature", "Target Temperature", "°C", EmulatorSignal.KIND_SINE, 18, 26, 1),
                    signal("humidity", "Humidity", "%", EmulatorSignal.KIND_SINE, 30, 75, 0),
                    signal("hvacState", "HVAC State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Idle", "Heating", "Cooling", "Fan"),
                    signal("motion", "Occupancy", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Away", "Home")),
            profile("smart-door-lock", "Smart Door Lock", CATEGORY_SMART_HOME, "Equipment", "LOCK-S3",
                    "Smart lock: state, battery, openings and tamper alarm.",
                    "lock", "#00897b", 10,
                    List.of("Home", "Away", "Guest Access", "Tamper Attempt"), "Home",
                    signal("lockState", "Lock State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Locked", "Unlocked"),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 20, 100, 0),
                    counter("openCount", "Openings", "pcs", 412, 0.02, 0),
                    signal("tamperAlarm", "Tamper Alarm", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Normal", "Tamper Detected"),
                    signal("lastUser", "Last User", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Owner", "Family", "Guest", "Unknown")),
            profile("smart-energy-plug", "Smart Energy Plug", CATEGORY_SMART_HOME, "Equipment", "PLUG-S1",
                    "Energy plug: instantaneous power, energy, voltage and relay state.",
                    "power", "#00897b", 10,
                    List.of("Device On", "Standby", "High Load", "Relay Off"), "Device On",
                    signal("power", "Power", "W", EmulatorSignal.KIND_SINE, 0, 2200, 0),
                    counter("energy", "Energy", "kWh", 328.4, 0.005, 3),
                    signal("voltage", "Voltage", "V", EmulatorSignal.KIND_SINE, 218, 232, 1),
                    signal("current", "Current", "A", EmulatorSignal.KIND_SINE, 0, 10, 2),
                    signal("relayState", "Relay State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "On", "Off")),
            profile("smoke-detector", "Smoke Detector", CATEGORY_SMART_HOME, "Sensor", "SMOKE-S1",
                    "Smoke detector with alarm, test and battery status.",
                    "detector_smoke", "#00897b", 30,
                    List.of("Normal", "Cooking Smoke", "Fire Alarm", "Low Battery"), "Normal",
                    signal("smokeLevel", "Smoke Level", "%/m", EmulatorSignal.KIND_SINE, 0, 25, 1),
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 18, 45, 1),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 15, 100, 0),
                    signal("alarmState", "Alarm State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Normal", "Test", "Alarm"),
                    signal("testState", "Test State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Ready", "Self Test")),
            profile("home-leak-sensor", "Home Leak Sensor", CATEGORY_SMART_HOME, "Sensor", "LEAK-S1",
                    "Leak sensor under the sink: moisture, temperature and valve state.",
                    "water_damage", "#00897b", 15,
                    List.of("Dry", "Leak Detected", "Valve Closed", "Low Battery"), "Dry",
                    signal("moisture", "Moisture", "%", EmulatorSignal.KIND_SINE, 0, 100, 0),
                    signal("temperature", "Temperature", "°C", EmulatorSignal.KIND_SINE, 12, 32, 1),
                    signal("battery", "Battery", "%", EmulatorSignal.KIND_RAMP, 20, 100, 0),
                    signal("alarmState", "Alarm State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Normal", "Leak Detected"),
                    signal("valveState", "Valve State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Open", "Closed")),

            // ===================================== Utilities =====================================
            profile("gas-meter", "Gas Meter", CATEGORY_UTILITIES, "Sensor", "GAS-M1",
                    "Residential gas meter: flow, volume, pressure and valve state.",
                    "local_fire_department", "#6d4c41", 30,
                    List.of("Normal Flow", "Peak Cooking", "No Flow", "Leak Alarm"), "Normal Flow",
                    signal("flowRate", "Flow Rate", "m³/h", EmulatorSignal.KIND_SINE, 0, 6, 2),
                    counter("volume", "Volume", "m³", 18420.35, 0.02, 2),
                    signal("pressure", "Pressure", "mbar", EmulatorSignal.KIND_SINE, 18, 30, 1),
                    signal("valveState", "Valve State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Open", "Closed")),
            profile("electricity-meter-residential", "Electricity Meter (Residential)", CATEGORY_UTILITIES,
                    "Equipment", "E-METER-R",
                    "Residential electricity meter with load profile and relay control.",
                    "electric_meter", "#6d4c41", 15,
                    List.of("Low Load", "Cooking Peak", "EV Charging", "Relay Off"), "Cooking Peak",
                    signal("activePower", "Active Power", "kW", EmulatorSignal.KIND_SINE, 0.1, 7.5, 2),
                    counter("energy", "Total Energy", "kWh", 24680.7, 0.005, 3),
                    signal("voltage", "Voltage", "V", EmulatorSignal.KIND_SINE, 218, 234, 1),
                    signal("current", "Current", "A", EmulatorSignal.KIND_SINE, 0.5, 32, 2),
                    signal("relayState", "Relay State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "On", "Off")),
            profile("water-utility-meter", "Water Utility Meter", CATEGORY_UTILITIES, "Sensor", "W-METER-R",
                    "Utility water meter: flow, volume, pressure and valve state.",
                    "water_drop", "#6d4c41", 30,
                    List.of("Normal Flow", "Night Leak", "No Flow", "Valve Closed"), "Normal Flow",
                    signal("flowRate", "Flow Rate", "m³/h", EmulatorSignal.KIND_SINE, 0, 3.5, 2),
                    counter("volume", "Volume", "m³", 1520.48, 0.002, 3),
                    signal("pressure", "Pressure", "bar", EmulatorSignal.KIND_SINE, 2, 5, 2),
                    signal("temperature", "Water Temperature", "°C", EmulatorSignal.KIND_SINE, 10, 28, 1),
                    signal("valveState", "Valve State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Open", "Closed")),
            profile("district-heating-meter", "District Heating Meter", CATEGORY_UTILITIES, "Sensor", "DH-METER",
                    "District heating meter with supply/return temperature and energy.",
                    "heat_pump", "#6d4c41", 30,
                    List.of("Heating Season", "Mild Day", "Night Setback", "Valve Closed"), "Heating Season",
                    signal("flowRate", "Flow Rate", "m³/h", EmulatorSignal.KIND_SINE, 0.2, 8, 2),
                    signal("supplyTemperature", "Supply Temperature", "°C", EmulatorSignal.KIND_SINE, 55, 85, 1),
                    signal("returnTemperature", "Return Temperature", "°C", EmulatorSignal.KIND_SINE, 35, 60, 1),
                    counter("energy", "Energy", "MWh", 386.24, 0.001, 3),
                    signal("valveState", "Valve State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0, "Open", "Closed")),
            profile("smart-transformer", "Smart Transformer", CATEGORY_UTILITIES, "System", "TRAFO-15",
                    "Distribution transformer: load, oil temperature, voltage and alarms.",
                    "electrical_services", "#6d4c41", 10,
                    List.of("Normal Load", "Peak Load", "Overheat", "Fault"), "Normal Load",
                    signal("load", "Load", "%", EmulatorSignal.KIND_SINE, 25, 95, 0),
                    signal("oilTemperature", "Oil Temperature", "°C", EmulatorSignal.KIND_SINE, 35, 85, 1),
                    signal("voltage", "Voltage", "V", EmulatorSignal.KIND_SINE, 380, 420, 1),
                    signal("current", "Current", "A", EmulatorSignal.KIND_SINE, 20, 320, 0),
                    signal("alarmState", "Alarm State", "state", EmulatorSignal.KIND_ENUM, 0, 0, 0,
                            "Normal", "Overload", "Overheat", "Fault"))
    );

    public List<EmulatorProfile> getProfiles() {
        return PROFILES;
    }

    public Optional<EmulatorProfile> findProfile(String profileId) {
        return PROFILES.stream().filter(profile -> profile.getId().equals(profileId)).findFirst();
    }

    public List<String> getCategories() {
        return PROFILES.stream().map(EmulatorProfile::getCategory).distinct().sorted().toList();
    }

    private static EmulatorProfile profile(String id, String name, String category, String type, String model,
                                           String description, String icon, String color, int intervalSeconds,
                                           List<String> scenarios, String defaultScenario,
                                           EmulatorSignal... signals) {
        EmulatorProfile profile = new EmulatorProfile();
        profile.setId(id);
        profile.setName(name);
        profile.setCategory(category);
        profile.setType(type);
        profile.setModel(model);
        profile.setDescription(description);
        profile.setIcon(icon);
        profile.setColor(color);
        profile.setIntervalSeconds(intervalSeconds);
        profile.setScenarios(scenarios);
        profile.setDefaultScenario(defaultScenario);
        profile.setSignals(List.of(signals));
        return profile;
    }

    private static EmulatorSignal signal(String key, String label, String unit, String kind,
                                         double min, double max, int decimals, String... values) {
        EmulatorSignal signal = new EmulatorSignal();
        signal.setKey(key);
        signal.setLabel(label);
        signal.setUnit(unit);
        signal.setKind(kind);
        signal.setMin(min);
        signal.setMax(max);
        signal.setDecimals(decimals);
        if (values.length > 0) {
            signal.setValues(Arrays.asList(values));
        }
        return signal;
    }

    /**
     * Monotonic counter (energy meters, odometers, production counters): it starts at {@code initial} — a realistic
     * reading of an equipment already in service — and grows by {@code rate} on every published value.
     */
    private static EmulatorSignal counter(String key, String label, String unit, double initial, double rate,
                                          int decimals) {
        EmulatorSignal signal = signal(key, label, unit, EmulatorSignal.KIND_COUNTER, 0, 0, decimals);
        signal.setRate(rate);
        signal.setInitialValue(initial);
        return signal;
    }

}
